### ISSUE TITLE
Upsample issue multiple bounding boxes

### ISSUE THREAD

**Issue by GuidoHeijden** [M-Nauta/ProtoTree#1]
Hi Meike,

Since I am not a collaborator on this repository, I am unable to push any changes. The problem for `upsample.py` where too large bounding boxes are drawn for a prototype image can be fixed by replacing lines 56-58 with the following code:
`# save the highly activated patch`
`masked_similarity_map = np.zeros(similarity_map.shape)`
`prototype_index = prototype_info['patch_ix']`
`masked_similarity_map[prototype_index // 7, prototype_index % 7] = 1`

Instead of finding the maximum value of the latent heatmap, the `project_info` is used for finding the location of the patch/prototype. The problem with the previous code was that the heatmap can contain multiple maxima.

Kind regards,
Guido

**Comment by M-Nauta** [comment]
This is indeed a small bug in the visualization part in the rare case of multiple maxima in the similarity map with exactly the same value. I have fixed the bug with an adapted version of your suggested solution, to prevent hard coding the size of the convolutional output.
