### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by pedrosbmartins** [M-Nauta/ProtoTree#2]
First of all, congrats on the very interesting paper!

I was wondering what architecture you used to train the model, and how much time it took. I'm trying to train on Colab with a GPU and it's taking ~40s per iteration (or ~5h per epoch). Is that the expected training time?

**Comment by M-Nauta** [comment]
We used a ResNet50 backbone in ProtoTree. As described in the supplementary material of the paper, ProtoTree only adds a small number of extra trainable parameters. Training time should therefore be comparable to (or slightly slower than) training a standard ResNet50 classifier. Expected training time depends on the type of GPU. What could help to speed up training is to increase the number of workers of the DataLoaders in the [get_dataloaders](https://github.com/M-Nauta/ProtoTree/blob/main/util/data.py#L30) function in `data.py` by setting `num_workers` to a positive integer value.

**Comment by pedrosbmartins** [comment]
Thanks a lot for the response and for the `num_workers` tip, the training did speed up substantially!

**Comment by M-Nauta** [comment]
Great to hear! I've included the `num_workers` tip in the README such that other users see it as well.
