### ISSUE TITLE
The requested URL /internal/car196/cars_train.tgz was not found on this server.

### ISSUE THREAD

**Issue by xymyys** [M-Nauta/ProtoTree#7]
Hi Meike,

Why does this error occur(The requested URL /internal/car196/cars_train.tgz was not found on this server) when downloading data sets according to the website?

**Comment by M-Nauta** [comment]
Hi,
This repository is now 2 years old so it could be that URLs have been changed in the mean time. It turns out that the CARS dataset has been moved, and this should be the new correct URL: http://ai.stanford.edu/~jkrause/car196/cars_train.tgz
